### ISSUE TITLE
Billing requested for PayPal Standard

### ISSUE THREAD

**Issue by KenzoFry** [strangerstudios/pmpro-variable-pricing#1]
Hi,

firstly thanks for PMPro and the additional plugins - magnificent work. 

I tested this out at my site, just to see if a 'pay what you want' method would be possible. I am using the PayPal Standard option. With this plugin, the checkout page started to ask for billing information, and then there's the PayPal button which takes you to PayPal and asks for billing info again.

Would fixing this just be a matter of adding PayPal standard to the list of 'no billing info' payment gateways?

Kenzo

**Comment by andrewlimaza** [comment]
Tested this and issue seems to have been resolved. :)
