### ISSUE TITLE
Feature Request -

### ISSUE THREAD

**Issue by travislima** [strangerstudios/pmpro-variable-pricing#11]
This Feature request came in from a user via our Members Forum.

A) Create an option to hide or display the "Your Price" **_placeholder_** text.

*_User note_ - "If it was blank, then people see the “Enter a price between $x and $y” line above, the “Your Price” label, and an empty box waiting to be filled. Easy and simple."

B) Create a dropdown style of preset selectable options.

**Further User notes:**

1. It should test for no entered value. At present, it is possible to proceed with no value and generate a not very helpful error message.  🙂

2. It would be great if this could be an option in the settings for users to choose if they wish to prefill a value or not.

**Comment by andrewlimaza** [comment]
We are kind of starting with some of these fixes in a different way. We are going to be adding real time notices if the value entered does not match the required amounts. User's may still try to checkout but an error will be thrown.

The placeholder text has been removed and you are able to allow a pre-filled value which was added fairly recently too. Marking this ticket as needs thought and discussion further with the team/user base :)
