### ISSUE TITLE
Variable price again on checkout using paypal express

### ISSUE THREAD

**Issue by peersyichi** [strangerstudios/pmpro-variable-pricing#3]
Thank you for the excellent plugins. I'm only having one small issue with checking out using variable pricing. After the paypal screen quoting the users variable price, the checkout page has a variable price instead of having the price the user picked at the beginning of the process. because of this, more billing details are needed when the user picks their price again. Is there anyway of carrying over the original quoted price to the checkout page so this isn't an issue.

Cheers again for these plugins. have saved me no no end of time,

Richie

**Comment by andrewlimaza** [comment]
I know this is a late reply, but latest update should fix this. Just tested and user's aren't able to adjust the price on the confirmation page.
