### ISSUE TITLE
Critical Issues in Site Health - interferes with REST API and loopback requests

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-variable-pricing#41]
When activated the Variable Pricing Add On is causing 2 Critical Issues in the Site Health.

`A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.`

and

`The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.`

The REST API request failed due to an error.
Error: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (http_request_failed)`

![critical-issue-variable-pricing](https://user-images.githubusercontent.com/8083630/148989290-69d921d4-123d-4cff-b3ac-484bbd887671.png)

Created with PMPro active, WordPress 5.8.3, PHP 7.4.27.

**Comment by michaelbeil** [comment]
As reported in ticket 401669 (**moderators only**).

> When activating “Variable Pricing Add On” our WordPress site triggers the following two critical issues.
> 
> 1: An Active PHP Session was detected
> 
> 2: The REST API encountered an error
> 
> Deactivating the plugin clears the error.

**Comment by michaelbeil** [comment]
Another customer opened up ticket 406209 (**moderators only**) regarding this: 
>In wordpress health, I encounter 2 issues……an active PHP session was detected & the REST API encountered an error. To figure out the plugin causing the errors, I read online to deactivate every plugin until the error disappears. I narrowed it down and it’s the variable price add-on plugin that is causing both critical errors. I currently don’t need it so I removed it and all works fine now.

**Comment by michaelbeil** [comment]
Another customer opened up ticket 424272 (**moderators only**) regarding this: 
>I have the Variable Pricing Add On installed. When I enable it, I start to see critical performance issues under the Site Health. I’ve isolated the issue to this plugin only. If I deactivate it the problem goes away immediately.

PR #36 fixes this.

**Comment by michaelbeil** [comment]
Another customer opened up ticket 441691 (**moderators only**) regarding this: 
>I have two critical issues with PHP and Rest API and I can’t get rid of them. 

I sent the [PR](https://github.com/strangerstudios/pmpro-variable-pricing/pull/36).

**Comment by michaelbeil** [comment]
Another customer opened up ticket 444723 (**moderators only**) regarding this, so I sent the [PR](https://github.com/strangerstudios/pmpro-variable-pricing/pull/36).

> When the variable pricing add-on is enabled, WP site health reports 2 critical issues. When the aforementioned add-on is disabled, the errors go away. I have gone as far as individually disabling each plugin installed on our site. When the PMP base plugin is disabled or when the variable pricing add-on is disabled, the 2 critical issues disappear and WP site health reports back with a “good” health report.

**Comment by michaelbeil** [comment]
A different customer opened up ticket 444934 (**moderators only**) regarding this, so I sent the [PR](https://github.com/strangerstudios/pmpro-variable-pricing/pull/36), which fixed the issue for the customer.

**Comment by michaelbeil** [comment]
A different customer in ticket 470672 (**moderators only**) regarding this, so I sent PR https://github.com/strangerstudios/pmpro-variable-pricing/pull/36.

> With the “Variable Pricing” add on enabled, in WordPress Site Health we get these errors:
> – An active PHP session was detected – A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.
> – The REST API encountered an error

**Comment by andrewlimaza** [comment]
This has been merged and queued for next release.
