### ISSUE TITLE
Order Total shows wrong value

### ISSUE THREAD

**Issue by IMAVF** [strangerstudios/pmpro-variable-pricing#5]
Hi,

in our membership levels we let the applicants choose between a min value of 40 € and a max value of 80 € (it is a yearly recurring fee). Checkout with PayPal Express works fine, the selected value is charged, but the order record shows the wrong total (80 €, which is the max value and also the value for "Initial Payment" and "Billing Amount" in the level setup; see attached screen shot).
Because of this, also the confirmation mail and the invoice history show the wrong value.

Finding a quick solution would be very much appreciated. Thanks!

![variable price](https://cloud.githubusercontent.com/assets/17496069/13354878/f27fcf98-dc9d-11e5-9ea1-2f69123da4ce.PNG)

**Comment by andrewlimaza** [comment]
We have tested this further and we are unable to recreate this issue. I assuming it has been resolved at some point in time. If this issue still persists, please open a new issue with steps to recreate or reach out to www.paidmembershipspro.com support channel.
