### ISSUE TITLE
Variable Pricing amount editable on Review Page

### ISSUE THREAD

**Issue by lok1728** [strangerstudios/pmpro-variable-pricing#7]
Upon returning from PayPal, the variable price input box is editable and should be greyed out. I don't think the pricing changes if a user inputs a different amount but it makes it confusing it this item is editable. If we're on the $pmpro_review page, this input should be disabled.

**Comment by andrewlimaza** [comment]
This has been resolved in one of the later updates for this Add On. If you are still experiencing this issue, please feel free to open a new Github issue with steps to recreate.
